# Generated by Django 2.1 on 2020-03-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200320_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='true_value',
        ),
        migrations.AlterField(
            model_name='item',
            name='highest_sell_price_trader',
            field=models.CharField(choices=[('Therapist', 'Therapist'), ('Skier', 'Skier'), ('Mechanic', 'Mechanic')], max_length=200),
        ),
    ]
