# Generated by Django 2.1 on 2020-03-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200320_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_slots',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_weight',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
