# Generated by Django 2.1 on 2020-03-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200321_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='highest_sell_price_trader',
            field=models.CharField(choices=[('Therapist', 'Therapist'), ('Skier', 'Skier'), ('Mechanic', 'Mechanic'), ('Prapor', 'Prapor')], max_length=200),
        ),
    ]
