version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/tarkovtrades/MongoDB:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  restapi:
    build: ./restapi
    ports:
      - 5000:5000
    volumes:
      - ~/tarkovtrades/restapi:/restapi

  gui:
    build: ./gui
    ports:
      - 8080:8080
    volumes:
      - ~/tarkovtrades/gui:/gui
