version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    volumes:
      - ~/tarkovtrades/MongoDB:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  flaskapp:
    build: ./FlaskAPI
    environment: 
      - FLASK_ENV=development
    ports:
      - 5000:5000
    volumes:
      - ~/tarkovtrades/FlaskAPI:/app

  gui:
    build: ./VueApp
    ports:
      - 8080:8080
    volumes:
      - ~/tarkovtrades/VueApp:/app
