# Generated by Django 2.2.11 on 2020-03-14 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200313_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lowest_buy_price_trader',
            field=models.CharField(blank=True, choices=[('', ''), ('Prapor', 'Prapor'), ('Therapist', 'Therapist'), ('Fence', 'Fence'), ('Skier', 'Skier'), ('Peacekeeper', 'Peacekeeper'), ('Mechanic', 'Mechanic'), ('Ragman', 'Ragman'), ('Jaeger', 'Jaeger')], default=('', ''), max_length=200),
        ),
    ]
