# Generated by Django 2.2.11 on 2020-03-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputcount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
        migrations.AlterField(
            model_name='inputcount',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trade'),
        ),
        migrations.AlterField(
            model_name='outputcount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item'),
        ),
        migrations.AlterField(
            model_name='outputcount',
            name='trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trade'),
        ),
    ]
