# Generated by Django 2.2.11 on 2020-03-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200313_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='true_value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
