# Generated by Django 2.2.11 on 2020-03-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_item_true_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='true_value',
        ),
        migrations.AddField(
            model_name='item',
            name='fee_to_post_at_buy_price_intel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='fee_to_post_at_buy_price_no_intel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
