# Generated by Django 2.2.11 on 2020-03-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200313_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fee_to_post_at_buy_price_intel',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='fee_to_post_at_buy_price_no_intel',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
