# Generated by Django 2.2.11 on 2020-03-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_truevaluecalc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrueValueCalc',
        ),
    ]
