# Generated by Django 2.1 on 2020-03-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200320_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='crafting_station_level',
            field=models.CharField(blank=True, choices=[('', ''), ('I', 'I'), ('II', 'II'), ('III', 'III')], default=('', ''), max_length=200),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trader_level',
            field=models.CharField(blank=True, choices=[('', ''), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('Max', 'Max')], default=('', ''), max_length=200),
        ),
    ]
